In [17]:
import numpy as np
x = np.arange(12).reshape((3,2,2))
x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [18]:
x.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [19]:
y = np.array([1,2,3],float)
y

array([1., 2., 3.])

In [20]:
y.dtype

dtype('float64')

In [21]:
np.array([(1,2.0),(3,4.0)],dtype=[('x',int),('y',float)])

array([(1, 2.), (3, 4.)], dtype=[('x', '<i8'), ('y', '<f8')])

In [22]:
np.random.randn(2, 3)

array([[ 1.5322927 ,  0.83265203,  0.50232336],
       [-0.28215494, -0.2314069 , -0.11296989]])

In [23]:
np.arange(10)
mask = np.arange(10)
print(mask)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
#use of function np.newaxis
arr = np.arange(4)
print(arr.shape)
print(arr)
row_vec = arr[:,np.newaxis]
print(row_vec)
row_vec.shape


(4,)
[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


(4, 1)

In [25]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1_new=x1[:,np.newaxis]
x1_new+x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [26]:
learning_rates = [1e-7, 5e-5]
regularization_strengths = [2.5e4, 5e4]

In [27]:
learning_rates

[1e-07, 5e-05]

In [28]:
from itertools import product   #cartesian product between data, the same as 
                                #nested loops
results = {}
for lr, reg in product(learning_rates, regularization_strengths):
    print(lr,"     ",reg)
    results[(lr, reg)] = (1,2)
    
results

1e-07       25000.0
1e-07       50000.0
5e-05       25000.0
5e-05       50000.0


{(1e-07, 25000.0): (1, 2),
 (1e-07, 50000.0): (1, 2),
 (5e-05, 25000.0): (1, 2),
 (5e-05, 50000.0): (1, 2)}

In [29]:

range(10)

range(0, 10)

In [31]:
x = np.array([2,3,4])
x

array([2, 3, 4])

In [36]:
Z -= np.random.randn(2, 3)
print(Z,"    ")
np.max(Z)

[[-3.75014575  0.64268126  0.31951302]
 [ 0.08314845  0.71464531  0.27387882]]     


0.7146453095924766